### ISSUE TITLE
Add new SPNEGO support to the documentation, Examples and possibly the client library

### ISSUE THREAD

**Issue by TheLydonKing** [AbsaOSS/login-service#104]
We recently added SPNEGO support via kerberos. It would be useful to add the new functionality to the other parts of the project including documentation, Client Library and Example clients.

Associated Issue: https://github.com/AbsaOSS/login-service/issues/100

```[tasklist]
### Tasks
- [ ] add spnego to examples
- [x] add spnego to documentation
- [ ] add spnego to client lib and adjust doc for this
```
