### ISSUE TITLE
Keys enhancements

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/login-service#48]
## Background
Currently, LS creates a single public-private key pair on startup. Good enough for simple usage, but for intended production use, we need some more features to cover expected usecases.

## Goal
See the individual tasks below. All aim to improve keys handling.

```[tasklist]
### Tasks
- [ ] https://github.com/AbsaOSS/login-gateway/issues/45
- [ ] https://github.com/AbsaOSS/login-gateway/issues/46
- [ ] https://github.com/AbsaOSS/login-gateway/issues/47
- [ ] https://github.com/AbsaOSS/login-service/issues/117
```
